services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest

  currency-db:
    image: redis:alpine

  budget-db:
    image: postgres:17-alpine

  currency.api:
    build:
      context: .
      dockerfile: Services/Currency/Currency.API/Dockerfile

  currency.grpc:
    build:
      context: .
      dockerfile: Services/Currency/Currency.GRPC/Dockerfile

  identityserver:
    build:
      context: .
      dockerfile: Security/IdentityServer/Dockerfile

  budget.api:
    build:
      context: .
      dockerfile: Services/Budget/Budget.API/Dockerfile

  budget.grpc:
    build:
      context: .
      dockerfile: Services/Budget/Budget.GRPC/Dockerfile
volumes:
  mssql_data:
  postgres_data:
