repos:
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1  # check for latest version
    hooks:
      - id: gitlint
        stages: [commit-msg]

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet-format
        entry: dotnet format
        language: system
        types_or: [c#, vb]
        stages: [pre-commit]
